#!/bin/bash
if [ "$(whoami)" == "root" ] ; then
	echo 'Creating directory /usr/local/piaf...'

	mkdir /usr/local/piaf
	echo 'Copying directory images to /usr/local/piaf...'
	cp -r main/images /usr/local/piaf
	echo "You may want to do chmod 777 /usr/local/piaf/images/pixmaps/ to enable user to update the icons, ..."
	echo
	echo 'Creating directory /etc/piaf...'
	mkdir /etc/piaf
	chmod 777 /etc/piaf
	echo 'Done.'
else 
	echo "FAILED : You must run install-piaf as root to create local install directories."
	exit 0
fi
echo 

echo

echo "Building piaf & plugins..."
./build.sh && echo "done" || echo "Please use ./prepare.sh to install needed packages for compilation (for ubuntu/debian)..."

if [ "$(whoami)" == "root" ] ; then
        echo 'installing directory /usr/local/piaf...'

	./build.sh install && echo "done" || echo "Please use ./prepare.sh to install needed packages for compilation (for ubuntu/debian)..."
fi


